/*
 * This source file was generated by the Gradle 'init' task
 */
package me.dvsgn

import org.junit.jupiter.api.Test
import org.junit.jupiter.api.Assertions.assertNotNull

class AppTest {
    @Test
    fun appHasAGreeting() {

    }
}
